In [42]:
import pandas as pd
import numpy as np

In [43]:
input_path = r"C:\\Users\\sharm\\OneDrive\\Desktop\\Kishan\\Contractzy\\WebScrapping\\Tutorial\\Financial_Data\\MoneyControl\\Companies\\IT Services & Consulting\\Tata Consultancy Services Ltd\\Pruned_Excel\\Pruned_Quarterly-resul_combined.xlsx"
output_path = r"C:\\Users\\sharm\\OneDrive\\Desktop\\Kishan\\Data\\Matrix_Text.txt"
new_output_path = r"C:\\Users\\sharm\\OneDrive\\Desktop\\Kishan\\Data\\transposed_Cash_flow.xlsx"

In [44]:
df = pd.read_excel(input_path)

In [45]:
df.head(5)

,Year,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,Quarterly Results of Tata Consultancy Services...,Net Sales/Income from operations,Total Income From Operations,Employees Cost,depreciat,Other Expenses,"P/L Before Other Inc. , Int., Excpt. Items & Tax",Other Income,"P/L Before Int., Excpt. Items & Tax",Interest,P/L Before Exceptional Items & Tax,P/L Before Tax,Tax,P/L After Tax from Ordinary Activities,Net Profit/(Loss) For the Period,Equity Share Capital,Basic EPS,Diluted EPS,Basic EPS.,Diluted EPS.
1,Dec '13,"16,692.65",16692.65,5430.93,280.36,5482.53,5498.83,653.13,6151.96,4,6147.96,6147.96,1371.2,4776.76,4776.76,195.87,24.36,24.36,24.36,24.36
2,Mar '14,"16,893.91",16893.91,5354.04,297.21,5974.83,5267.83,685.89,5953.72,4.55,5949.17,5949.17,1320.65,4628.52,4628.52,195.87,23.54,23.54,23.54,23.54
3,Jun '14,"17,438.43",17438.43,6024.84,335.26,5925.38,5152.95,798.96,5951.91,3.73,5948.18,6475.94,1379.07,5096.87,5096.87,195.87,26.02,26.02,26.02,26.02
4,Sep '14,"18,405.05",18405.05,6260.67,340.71,6243,5560.67,865.17,6425.84,58.14,6367.7,6367.7,1376.02,4991.68,4991.68,195.87,25.48,25.48,25.48,25.48

In [46]:
df.columns

Index(['Year', 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17,
       18],
      dtype='object')

In [47]:
# Set the first row as the column headers and remove it from the data
df.columns = df.iloc[0]  # Set first row as column headers
df = df[1:].reset_index(drop=True)  # Remove the first row

# Convert columns to numeric where possible
df = df.apply(pd.to_numeric, errors='coerce')

# Compute and display the correlation matrix
correlation_matrix = df.corr()
print(correlation_matrix)

with open(output_path,"w") as f:
    f.write(str(correlation_matrix))

0                                                   Quarterly Results of Tata Consultancy Services(in Rs. Cr.)  \
0
Quarterly Results of Tata Consultancy Services(...                                                NaN
Net Sales/Income from operations                                                                  NaN
Total Income From Operations                                                                      NaN
Employees Cost                                                                                    NaN
depreciat                                                                                         NaN
Other Expenses                                                                                    NaN
P/L Before Other Inc. , Int., Excpt. Items & Tax                                                  NaN
Other Income                                                                                      NaN
P/L Before Int., Excpt. Items & Tax                                                               NaN
Interest                                                                                          NaN
P/L Before Exceptional Items & Tax                                                                NaN
P/L Before Tax                                                                                    NaN
Tax                                                                                               NaN
P/L After Tax from Ordinary Activities                                                            NaN
Net Profit/(Loss) For the Period                                                                  NaN
Equity Share Capital                                                                              NaN
Basic EPS                                                                                         NaN
Diluted EPS                                                                                       NaN
Basic EPS.                                                                                        NaN
Diluted EPS.                                                                                      NaN

0                                                   Net Sales/Income from operations  \
0
Quarterly Results of Tata Consultancy Services(...                               NaN
Net Sales/Income from operations                                                 NaN
Total Income From Operations                                                     NaN
Employees Cost                                                                   NaN
depreciat                                                                        NaN
Other Expenses                                                                   NaN
P/L Before Other Inc. , Int., Excpt. Items & Tax                                 NaN
Other Income                                                                     NaN
P/L Before Int., Excpt. Items & Tax                                              NaN
Interest                                                                         NaN
P/L Before Exceptional Items & Tax                                               NaN
P/L Before Tax                                                                   NaN
Tax                                                                              NaN
P/L After Tax from Ordinary Activities                                           NaN
Net Profit/(Loss) For the Period                                                 NaN
Equity Share Capital                                                             NaN
Basic EPS                                                                        NaN
Diluted EPS                                                                      NaN
Basic EPS.                                                                       NaN
Diluted EPS.                                                                     NaN

0                                                   Total Income From Operations  \
0
Quarterly Results of Tata Consultancy Services(...                           NaN
Net Sales/Income from operations                                             NaN
Total Income From Operations                                            1.000000
Employees Cost                                                          0.988807
depreciat                                                               0.961901
Other Expenses                                                          0.927162
P/L Before Other Inc. , Int., Excpt. Items & Tax                        0.983726
Other Income                                                            0.540981
P/L Before Int., Excpt. Items & Tax                                     0.974313
Interest                                                                0.798200
P/L Before Exceptional Items & Tax                                      0.973214
P/L Before Tax                                                          0.971927
Tax                                                                     0.958101
P/L After Tax from Ordinary Activities                                  0.962808
Net Profit/(Loss) For the Period                                        0.962808
Equity Share Capital                                                    0.787176
Basic EPS                                                               0.192346
Diluted EPS                                                             0.192346
Basic EPS.                                                              0.192389
Diluted EPS.                                                            0.192346

0                                                   Employees Cost  depreciat  \
0
Quarterly Results of Tata Consultancy Services(...             NaN        NaN
Net Sales/Income from operations                               NaN        NaN
Total Income From Operations                              0.988807   0.961901
Employees Cost                                            1.000000   0.951905
depreciat                                                 0.951905   1.000000
Other Expenses                                            0.868538   0.884833
P/L Before Other Inc. , Int., Excpt. Items & Tax          0.966193   0.943807
Other Income                                              0.538468   0.467283
P/L Before Int., Excpt. Items & Tax                       0.958360   0.924523
Interest                                                  0.775977   0.846585
P/L Before Exceptional Items & Tax                        0.957515   0.921179
P/L Before Tax                                            0.954506   0.918168
Tax                                                       0.938250   0.892833
P/L After Tax from Ordinary Activities                    0.946484   0.913827
Net Profit/(Loss) For the Period                          0.946484   0.913827
Equity Share Capital                                      0.772216   0.780692
Basic EPS                                                 0.210665   0.123955
Diluted EPS                                               0.210665   0.123955
Basic EPS.                                                0.210724   0.124062
Diluted EPS.                                              0.210665   0.123955

0                                                   Other Expenses  \
0
Quarterly Results of Tata Consultancy Services(...             NaN
Net Sales/Income from operations                               NaN
Total Income From Operations                              0.927162
Employees Cost                                            0.868538
depreciat                                                 0.884833
Other Expenses                                            1.000000
P/L Before Other Inc. , Int., Excpt. Items & Tax          0.893602
Other Income                                              0.504906
P/L Before Int., Excpt. Items & Tax                       0.887724
Interest                                                  0.757113
P/L Before Exceptional Items & Tax                        0.885952
P/L Before Tax                                            0.891584
Tax                                                       0.889749
P/L After Tax from Ordinary Activities                    0.879443
Net Profit/(Loss) For the Period                          0.879443
Equity Share Capital                                      0.726467
Basic EPS                                                 0.104578
Diluted EPS                                               0.104578
Basic EPS.                                                0.104537
Diluted EPS.                                              0.104578

0                                                   P/L Before Other Inc. , Int., Excpt. Items & Tax  \
0
Quarterly Results of Tata Consultancy Services(...                                               NaN
Net Sales/Income from operations                                                                 NaN
Total Income From Operations                                                                0.983726
Employees Cost                                                                              0.966193
depreciat                                                                                   0.943807
Other Expenses                                                                              0.893602
P/L Before Other Inc. , Int., Excpt. Items & Tax                                            1.000000
Other Income                                                                                0.526050
P/L Before Int., Excpt. Items & Tax                                                         0.985699
Interest                                                                                    0.792391
P/L Before Exceptional Items & Tax                                                          0.984978
P/L Before Tax                                                                              0.981553
Tax                                                                                         0.964875
P/L After Tax from Ordinary Activities                                                      0.973289
Net Profit/(Loss) For the Period                                                            0.973289
Equity Share Capital                                                                        0.789344
Basic EPS                                                                                   0.216312
Diluted EPS                                                                                 0.216312
Basic EPS.                                                                                  0.216383
Diluted EPS.                                                                                0.216312

0                                                   Other Income  \
0
Quarterly Results of Tata Consultancy Services(...           NaN
Net Sales/Income from operations                             NaN
Total Income From Operations                            0.540981
Employees Cost                                          0.538468
depreciat                                               0.467283
Other Expenses                                          0.504906
P/L Before Other Inc. , Int., Excpt. Items & Tax        0.526050
Other Income                                            1.000000
P/L Before Int., Excpt. Items & Tax                     0.661841
Interest                                                0.414283
P/L Before Exceptional Items & Tax                      0.664394
P/L Before Tax                                          0.663930
Tax                                                     0.582551
P/L After Tax from Ordinary Activities                  0.682741
Net Profit/(Loss) For the Period                        0.682741
Equity Share Capital                                    0.542027
Basic EPS                                               0.186733
Diluted EPS                                             0.186733
Basic EPS.                                              0.186816
Diluted EPS.                                            0.186733

0                                                   P/L Before Int., Excpt. Items & Tax  \
0
Quarterly Results of Tata Consultancy Services(...                                  NaN
Net Sales/Income from operations                                                    NaN
Total Income From Operations                                                   0.974313
Employees Cost                                                                 0.958360
depreciat                                                                      0.924523
Other Expenses                                                                 0.887724
P/L Before Other Inc. , Int., Excpt. Items & Tax                               0.985699
Other Income                                                                   0.661841
P/L Before Int., Excpt. Items & Tax                                            1.000000
Interest                                                                       0.780553
P/L Before Exceptional Items & Tax                                             0.999870
P/L Before Tax                                                                 0.996759
Tax                                                                            0.965933
P/L After Tax from Ordinary Activities                                         0.993202
Net Profit/(Loss) For the Period                                               0.993202
Equity Share Capital                                                           0.803180
Basic EPS                                                                      0.227672
Diluted EPS                                                                    0.227672
Basic EPS.                                                                     0.227751
Diluted EPS.                                                                   0.227672

0                                                   Interest  \
0
Quarterly Results of Tata Consultancy Services(...       NaN
Net Sales/Income from operations                         NaN
Total Income From Operations                        0.798200
Employees Cost                                      0.775977
depreciat                                           0.846585
Other Expenses                                      0.757113
P/L Before Other Inc. , Int., Excpt. Items & Tax    0.792391
Other Income                                        0.414283
P/L Before Int., Excpt. Items & Tax                 0.780553
Interest                                            1.000000
P/L Before Exceptional Items & Tax                  0.770371
P/L Before Tax                                      0.761117
Tax                                                 0.723133
P/L After Tax from Ordinary Activities              0.763430
Net Profit/(Loss) For the Period                    0.763430
Equity Share Capital                                0.795000
Basic EPS                                          -0.107274
Diluted EPS                                        -0.107274
Basic EPS.                                         -0.107168
Diluted EPS.                                       -0.107274

0                                                   P/L Before Exceptional Items & Tax  \
0
Quarterly Results of Tata Consultancy Services(...                                 NaN
Net Sales/Income from operations                                                   NaN
Total Income From Operations                                                  0.973214
Employees Cost                                                                0.957515
depreciat                                                                     0.921179
Other Expenses                                                                0.885952
P/L Before Other Inc. , Int., Excpt. Items & Tax                              0.984978
Other Income                                                                  0.664394
P/L Before Int., Excpt. Items & Tax                                           0.999870
Interest                                                                      0.770371
P/L Before Exceptional Items & Tax                                            1.000000
P/L Before Tax                                                                0.997066
Tax                                                                           0.966603
P/L After Tax from Ordinary Activities                                        0.993378
Net Profit/(Loss) For the Period                                              0.993378
Equity Share Capital                                                          0.798739
Basic EPS                                                                     0.234994
Diluted EPS                                                                   0.234994
Basic EPS.                                                                    0.235072
Diluted EPS.                                                                  0.234994

0                                                   P/L Before Tax       Tax  \
0
Quarterly Results of Tata Consultancy Services(...             NaN       NaN
Net Sales/Income from operations                               NaN       NaN
Total Income From Operations                              0.971927  0.958101
Employees Cost                                            0.954506  0.938250
depreciat                                                 0.918168  0.892833
Other Expenses                                            0.891584  0.889749
P/L Before Other Inc. , Int., Excpt. Items & Tax          0.981553  0.964875
Other Income                                              0.663930  0.582551
P/L Before Int., Excpt. Items & Tax                       0.996759  0.965933
Interest                                                  0.761117  0.723133
P/L Before Exceptional Items & Tax                        0.997066  0.966603
P/L Before Tax                                            1.000000  0.969348
Tax                                                       0.969348  1.000000
P/L After Tax from Ordinary Activities                    0.996336  0.944783
Net Profit/(Loss) For the Period                          0.996336  0.944783
Equity Share Capital                                      0.793248  0.827086
Basic EPS                                                 0.246256  0.122618
Diluted EPS                                               0.246256  0.122618
Basic EPS.                                                0.246321  0.122666
Diluted EPS.                                              0.246256  0.122618

0                                                   P/L After Tax from Ordinary Activities  \
0
Quarterly Results of Tata Consultancy Services(...                                     NaN
Net Sales/Income from operations                                                       NaN
Total Income From Operations                                                      0.962808
Employees Cost                                                                    0.946484
depreciat                                                                         0.913827
Other Expenses                                                                    0.879443
P/L Before Other Inc. , Int., Excpt. Items & Tax                                  0.973289
Other Income                                                                      0.682741
P/L Before Int., Excpt. Items & Tax                                               0.993202
Interest                                                                          0.763430
P/L Before Exceptional Items & Tax                                                0.993378
P/L Before Tax                                                                    0.996336

In [48]:
print(df.head())

0  Quarterly Results of Tata Consultancy Services(in Rs. Cr.)  \
0                                                NaN
1                                                NaN
2                                                NaN
3                                                NaN
4                                                NaN

0  Net Sales/Income from operations  Total Income From Operations  \
0                               NaN                      16692.65
1                               NaN                      16893.91
2                               NaN                      17438.43
3                               NaN                      18405.05
4                               NaN                      18936.35

0  Employees Cost  depreciat  Other Expenses  \
0         5430.93     280.36         5482.53
1         5354.04     297.21         5974.83
2         6024.84     335.26         5925.38
3         6260.67     340.71         6243.00
4         6440.38     350.51         6354.75

0  P/L Before Other Inc. , Int., Excpt. Items & Tax  Other Income  \
0                                           5498.83        653.13
1                                           5267.83        685.89
2                                           5152.95        798.96
3                                           5560.67        865.17
4                                           5790.71       1503.16

0  P/L Before Int., Excpt. Items & Tax  Interest  \
0                              6151.96      4.00
1                              5953.72      4.55
2                              5951.91      3.73
3                              6425.84     58.14
4                              7293.87     12.54

0  P/L Before Exceptional Items & Tax  P/L Before Tax      Tax  \
0                             6147.96         6147.96  1371.20
1                             5949.17         5949.17  1320.65
2                             5948.18         6475.94  1379.07
3                             6367.70         6367.70  1376.02
4                             7281.33         7281.33  1570.18

0  P/L After Tax from Ordinary Activities  Net Profit/(Loss) For the Period  \
0                                 4776.76                           4776.76
1                                 4628.52                           4628.52
2                                 5096.87                           5096.87
3                                 4991.68                           4991.68
4                                 5711.15                           5711.15

0  Equity Share Capital  Basic EPS  Diluted EPS  Basic EPS.  Diluted EPS.
0                195.87      24.36        24.36       24.36         24.36
1                195.87      23.54        23.54       23.54         23.54
2                195.87      26.02        26.02       26.02         26.02
3                195.87      25.48        25.48       25.48         25.48
4                195.87      29.16        29.16       29.16         29.16